services:
  app:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=dev
    env_file:
      - .env
    command: npm run dev
    restart: unless-stopped
  minio:
    restart: no
  rabbitmq:
    restart: unless-stopped
  minio-client:
    restart: no
