services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - minio
      - rabbitmq
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:4.1.2-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
    networks:
      - app-network

volumes:
  minio_data:
  rabbitmq_data:
    driver: local

networks:
  app-network:
    driver: bridge
