services:
  stream:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:9005"
    depends_on:
      - rabbitmq
    networks:
      - vellum-network

  rabbitmq:
    image: rabbitmq:4.1.2-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    # ports:
    #   - "5672:5672"
    #   - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
    networks:
      - vellum-network

volumes:
  rabbitmq_data:
    driver: local

networks:
  vellum-network:
    driver: bridge
